/**
 * Audit Report PDF Template — Individual Engagement Form
 * =======================================================
 * Renders the Compliance & Audit Report PDF for Individual Client Engagements.
 * Styled in Financially Up brand primary (#008043) & soft light (#eaf7f0) theme.
 */

const path = require("path");
const fs = require("fs");

function getLogoBase64Uri() {
  try {
    const logoPath = path.join(__dirname, "../../../public/images/logo.png");
    if (fs.existsSync(logoPath)) {
      const buffer = fs.readFileSync(logoPath);
      return `data:image/png;base64,${buffer.toString("base64")}`;
    }
  } catch (e) {}
  return process.env.COMPANY_LOGO_URL || "http://localhost:5000/images/logo.png";
}

function renderAuditReportHtml(data) {
  const referenceNumber = data.referenceNumber || `NENG-${Date.now()}`;
  const client = data.client || {};
  const auditLogs = data.auditLogs || [];
  const pdfs = data.pdfs || [];
  const logoUri = getLogoBase64Uri();
  const now = new Date();

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${referenceNumber}_Audit_Report</title>
  <style>
    @page { size: A4; margin: 20mm 15mm 20mm 15mm; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #0f172a; margin: 0; padding: 0; font-size: 11px; line-height: 1.5; }
    
    .header-banner { border-bottom: 3px solid #008043; padding-bottom: 12px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; }
    .brand-logo { max-height: 44px; max-width: 200px; object-fit: contain; }
    .brand-subtitle { font-size: 10px; color: #008043; font-weight: 800; text-transform: uppercase; margin-top: 2px; letter-spacing: 0.3px; }
    .ref-badge { background: #eaf7f0; border: 1px solid #a7f3d0; color: #065f46; padding: 6px 12px; border-radius: 8px; font-family: monospace; font-size: 12px; font-weight: bold; }
    
    .section-head { font-size: 12px; font-weight: 800; color: #008043; background: #eaf7f0; border-left: 4px solid #008043; padding: 5px 8px; margin-top: 20px; margin-bottom: 10px; text-transform: uppercase; letter-spacing: 0.3px; }
    
    table { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
    th, td { border: 1px solid #cbd5e1; padding: 6px 9px; font-size: 10px; text-align: left; }
    th { background: #f8fafc; font-weight: 700; color: #334155; }

    .footer { position: fixed; bottom: 0; left: 0; right: 0; text-align: center; font-size: 9px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 6px; }
  </style>
</head>
<body>

  <!-- Header Banner with Logo -->
  <div class="header-banner">
    <div>
      <img src="${logoUri}" class="brand-logo" alt="Financially Up" />
      <div class="brand-subtitle">Compliance, Audit Trail & Document Version Log</div>
    </div>
    <div class="ref-badge">
      AUDIT: ${referenceNumber}
    </div>
  </div>

  <!-- Section 1: Engagement Summary -->
  <div class="section-head">1. Engagement Metadata</div>
  <table>
    <tr><th>Reference Number</th><td>${referenceNumber}</td><th>Client Name</th><td>${client.fullName || 'N/A'}</td></tr>
    <tr><th>Current Status</th><td>${data.status || 'Pending Review'}</td><th>Risk Level</th><td>${data.riskLevel || 'Low'}</td></tr>
    <tr><th>Report Generated At</th><td>${now.toLocaleString('en-AU')}</td><th>Generated By</th><td>Compliance Auditor</td></tr>
  </table>

  <!-- Section 2: PDF Document Version History -->
  <div class="section-head">2. PDF Document Manifest & Version Control</div>
  <table>
    <thead>
      <tr>
        <th>Type</th>
        <th>File Name</th>
        <th>Version</th>
        <th>Generated At</th>
        <th>Email Status</th>
      </tr>
    </thead>
    <tbody>
      ${pdfs.length > 0 ? pdfs.map((p) => `
        <tr>
          <td><strong>${p.type}</strong></td>
          <td style="font-family: monospace;">${p.fileName}</td>
          <td>v${p.version || 1} (${p.templateVersion || 'v1.0.0'})</td>
          <td>${new Date(p.generatedAt).toLocaleString('en-AU')}</td>
          <td>${p.emailSent ? 'Sent' : 'Pending'}</td>
        </tr>
      `).join('') : `
        <tr><td colspan="5" style="text-align: center; color: #94a3b8;">No PDF version logs recorded yet.</td></tr>
      `}
    </tbody>
  </table>

  <!-- Section 3: Audit Log Events -->
  <div class="section-head">3. System Action Logs</div>
  <table>
    <thead>
      <tr>
        <th>Timestamp</th>
        <th>Action</th>
        <th>Performed By</th>
        <th>IP Address</th>
      </tr>
    </thead>
    <tbody>
      ${auditLogs.length > 0 ? auditLogs.map((log) => `
        <tr>
          <td>${new Date(log.createdAt).toLocaleString('en-AU')}</td>
          <td><strong>${log.action}</strong></td>
          <td>${log.performedBy}</td>
          <td style="font-family: monospace;">${log.ipAddress || 'N/A'}</td>
        </tr>
      `).join('') : `
        <tr>
          <td>${now.toLocaleString('en-AU')}</td>
          <td><strong>CLIENT_FORM_SUBMITTED</strong></td>
          <td>Client (${client.fullName})</td>
          <td style="font-family: monospace;">127.0.0.1</td>
        </tr>
      `}
    </tbody>
  </table>

  <!-- Footer -->
  <div class="footer">
    INTERNAL AUDIT REPORT — FINANCIALLY UP AUDIT & COMPLIANCE SYSTEM
  </div>

</body>
</html>
  `;
}

module.exports = { renderAuditReportHtml };
